import { SortBy } from './type'

export const TableColWidth = {
  name: 160,
  price: 100,
  mkc: 95,
  vol: 95,
  liquidity: 95,
  mkcliq: 85,
  changePercent: 75,
  link: 260,
  action: 80,
}

export const Columns = [
  {
    name: 'Name',
    justifyContent: 'flex-start',
    width: TableColWidth.name,
    hoverDisable: true,
    paddingRight: 0,
    paddingLeft: 10,
    sortBy: null,
  },
  {
    name: 'Price',
    justifyContent: 'flex-end',
    width: TableColWidth.price,
    hoverDisable: false,
    paddingRight: 8,
    sortBy: SortBy.PRICE,
  },
  {
    name: 'MKC',
    justifyContent: 'flex-end',
    width: TableColWidth.mkc,
    hoverDisable: false,
    paddingRight: 8,
    sortBy: SortBy.MARKETCAP,
  },
  {
    name: 'Liquidity',
    justifyContent: 'flex-end',
    width: TableColWidth.liquidity,
    hoverDisable: false,
    paddingRight: 8,
    sortBy: SortBy.LIQ,
  },
  {
    name: 'Volume',
    justifyContent: 'flex-end',
    width: TableColWidth.vol,
    hoverDisable: false,
    paddingRight: 8,
    sortBy: SortBy.VOLUME,
  },
  {
    name: 'Hour',
    justifyContent: 'flex-end',
    width: TableColWidth.changePercent,
    hoverDisable: false,
    paddingRight: 8,
    sortBy: SortBy.HOUR,
  },
  {
    name: '6H',
    justifyContent: 'flex-end',
    width: TableColWidth.changePercent,
    hoverDisable: false,
    paddingRight: 8,
    sortBy: SortBy.SIXHOURS,
  },
  {
    name: 'Day',
    justifyContent: 'flex-end',
    width: TableColWidth.changePercent,
    hoverDisable: false,
    paddingRight: 8,
    sortBy: SortBy.DAY,
  },
  {
    name: 'Week',
    justifyContent: 'flex-end',
    width: TableColWidth.changePercent,
    hoverDisable: false,
    paddingRight: 8,
    sortBy: SortBy.WEEK,
  },
  {
    name: 'Month',
    justifyContent: 'flex-end',
    width: TableColWidth.changePercent,
    hoverDisable: false,
    paddingRight: 8,
    sortBy: SortBy.MONTH,
  },
  {
    name: 'Year',
    justifyContent: 'flex-end',
    width: TableColWidth.changePercent,
    hoverDisable: false,
    paddingRight: 8,
    sortBy: SortBy.YEAR,
  },
  {
    name: '',
    justifyContent: 'center',
    width: TableColWidth.action,
    hoverDisable: true,
    paddingRight: 0,
    sortBy: null,
  },
]
