export const tokensList: Array<any> = [
  {
    coingeckoId: 'official-trump',
    symbol: 'TRUMP',
    name: 'OFFICIAL TRUMP',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/53746/large/trump.png?1737171561',
    address: '6p6xgHyF7AeE6TZkSmFsko444wqoP15icUSqi2jfGiPN',
    pairAddress: '9d9mb8kooFfaD3SctgZtkxQypkshx6ezhbKio89ixyy2',
    website: 'https://x.com/realDonaldTrump/status/1880446012168249386',
    x: 'https://x.com/GetTrumpMemes',
    telegram: '',
  },
  {
    coingeckoId: 'jupiter-exchange-solana',
    symbol: 'JUP',
    name: 'Jupiter',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/34188/large/jup.png?1704266489',
    address: 'JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN',
    pairAddress: '7qt1qBnQ5CNNpMH1no6jYAzuyazP5QWXsUZB7dot5kga',
    website: 'https://jup.ag',
    x: 'https://twitter.com/JupiterExchange',
    telegram: '',
  },
  {
    coingeckoId: 'render-token',
    symbol: 'RENDER',
    name: 'Render Token',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/11636/large/rndr.png?1696511529',
    address: 'rndrizKT3MK1iimdxRdWabcF7Zg7AR5T4nud4EkHBof',
    pairAddress: 'FZ8MJvdTPbp8juhtFCCzb7LsKunhexgzShGQ59SUJkNL',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'bonk',
    symbol: 'Bonk',
    name: 'Bonk',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/28600/large/bonk.jpg?1696527587',
    address: 'DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263',
    pairAddress: '6oFWm7KPLfxnwMb3z5xwBoXNSPP3JJyirAPqPSiVcnsp',
    website: 'https://www.bonkcoin.com',
    x: 'https://twitter.com/bonk_inu',
    telegram: 'https://t.me/Official_Bonk_Inu',
  },

  {
    coingeckoId: 'pyth-network',
    symbol: 'PYTH',
    name: 'Pyth Network',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/31924/large/pyth.png?1701245725',
    address: 'HZ1JovNiVvGrGNiiYvEozEVgZ58xaU3RKwX8eACQBCt3',
    pairAddress: '9n3dSLrERZQp95dHXywft7xV8D8xnGFLaUHtEhQVaXaC',
    website: 'https://pyth.network',
    x: 'https://twitter.com/PythNetwork',
    telegram: 'https://telegram.me/Pyth_Network',
  },
  {
    coingeckoId: 'jito-governance-token',
    symbol: 'JTO',
    name: 'JITO',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/33228/large/jto.png?1701137022',
    address: 'jtojtomepa8beP8AuQc6eXt5FriJwfFMwQx2v2f9mCL',
    pairAddress: 'G2FiE1yn9N9ZJx5e1E2LxxMnHvb1H3hCuHLPfKJ98smA',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'virtual-protocol',
    symbol: 'VIRTUAL',
    name: 'Virtual Protocol',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/34057/large/LOGOMARK.png?1708356054',
    address: '3iQL8BFS2vE7mww4ehAqQHAsbmRNCrPxizWAT2Zfyr9y',
    pairAddress: 'B1AdQ85N2mJ2xtMg9bgThhsPoA6T3M26rt4TChWSiPpr',
    website: 'https://app.virtuals.io/',
    x: 'https://x.com/virtuals_io',
    telegram: 'https://t.me/virtuals',
  },

  {
    coingeckoId: 'raydium',
    symbol: 'RAY',
    name: 'Raydium',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/13928/large/PSigc4ie_400x400.jpg?1696513668',
    address: '4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R',
    pairAddress: '2AXXcN6oN9bBT5owwmTH53C7QHUXvhLeu718Kqt8rvY2',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'dogwifcoin',
    symbol: '$WIF',
    name: 'dogwifhat',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/33566/large/dogwifhat.jpg?1702499428',
    address: 'EKpQGSJtjMFqKZ9KQanSqYXRcF8fBopzLHYxdM65zcjm',
    pairAddress: 'EP2ib6dYdEeqD8MfE2ezHCxX3kP3K2eLKkirfPm5eyMx',
    website: 'https://dogwifcoin.org',
    x: 'https://twitter.com/dogwifcoin',
    telegram: 'https://t.me/dogwifcoin',
  },
  {
    coingeckoId: 'helium',
    symbol: 'HNT',
    name: 'Helium Network Token',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/4284/large/Helium_HNT.png?1696504894',
    address: 'hntyVP6YFm1Hg25TN9WGLqM12b8TQmcknKrdu1oxWux',
    pairAddress: '5qrvgpvr55Eo7c5bBcwopdiQ6TpvceiRm42yjHTbtDvc',
    website: '',
    x: '',
    telegram: '',
  },

  {
    coingeckoId: 'pudgy-penguins',
    symbol: 'PENGU',
    name: 'Pudgy Penguins',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/52622/large/PUDGY_PENGUINS_PENGU_PFP.png?1733809110',
    address: '2zMMhcVQEXDtdE6vsFS7S7D5oUodfJHE8vd1gnBouauv',
    pairAddress: 'B4Vwozy1FGtp8SELXSXydWSzavPUGnJ77DURV2k4MhUV',
    website: 'https://www.pudgypenguins.com',
    x: 'https://x.com/pudgypenguins',
    telegram: '',
  },
  {
    coingeckoId: 'grass',
    symbol: 'GRASS',
    name: 'Grass',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/40094/large/Grass.jpg?1725697048',
    address: 'Grass7B4RdKfBCjTKgSqnXkqjwiGvQyFbuSCUJr3XXjs',
    pairAddress: 'GTJ2S27UL7yZ3TdTwpKjfNcxeEZRkRPHjpj5Fubwb8Mk',
    website: 'https://www.getgrass.io/',
    x: 'https://x.com/getgrass_io',
    telegram: '',
  },
  {
    coingeckoId: 'spx6900',
    symbol: 'SPX',
    name: 'SPX6900 (Wormhole)',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/31401/large/centeredcoin_%281%29.png?1737048493',
    address: 'J3NKxxXZcnNiMjKw9hYb2K4LUxgwB6t1FtPtQVsv3KFr',
    pairAddress: '9t1H1uDJ558iMPNkEPSN1fqkpC4XSPQ6cqSf6uEsTfTR',
    website: 'https://www.spx6900.com/',
    x: 'https://twitter.com/spx6900',
    telegram: 'https://t.me/SPX6900Portal',
  },
  {
    coingeckoId: 'ousg',
    symbol: 'ousg',
    name: 'OUSG',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/29023/large/OUSG.png?1696527993',
    address: 'i7u4r16TcsJTgq1kAG8opmVZyVnAKBwLKu6ZPMwzxNc',
  },
  {
    coingeckoId: 'wormhole',
    symbol: 'W',
    name: 'Wormhole Token',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/35087/large/womrhole_logo_full_color_rgb_2000px_72ppi_fb766ac85a.png?1708688954',
    address: '85VBFQZC9TZkfaptBWjvUw7YbZjy52A6mjtPGjstQAmQ',
    pairAddress: 'CwHuXNNkj5inuj2ZXaU1DtjA5Nxfoiy4nNoc1PQQJxTR',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'meow',
    symbol: 'meow',
    name: 'Meow',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/38796/large/MEOW.png?1718897555',
    address: 'BUhS5coXEt9hcxN3JSpGYUWSKbNo96RsKu52LcMo12rf',
    pairAddress: 'DxVSVREMYuysA7PsZk76wDhjJuuKE7fdt3uYTKX4fank',
    website: 'https://meowfi.io/home',
    x: 'https://twitter.com/meowmeowcatclub',
    telegram: 'https://t.me/meowie_gang',
  },
  {
    coingeckoId: 'ai16z',
    symbol: 'ai16z',
    name: 'ai16z',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/51090/large/AI16Z.jpg?1730027175',
    address: 'HeLp6NuQkmYB4pYWo2zYs22mESHXPQYzXbB8n4V98jwC',
    pairAddress: '8sN9549P3Zn6xpQRqpApN57xzkCh6sJxLwuEjcG2W4Ji',
    website: 'https://elizaos.ai/',
    x: 'https://x.com/ai16zdao',
    telegram: 'https://t.me/elizaOSdev',
  },
  {
    coingeckoId: 'fartcoin',
    symbol: 'Fartcoin ',
    name: 'Fartcoin ',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/50891/large/fart.jpg?1729503972',
    address: '9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump',
    pairAddress: 'Bzc9NZfMqkXR6fz1DBph7BDf9BroyEf6pnzESP7v5iiw',
    website:
      'https://www.infinitebackrooms.com/dreams/conversation-1721540624-scenario-terminal-of-truths-txt',
    x: 'https://x.com/FartCoinOfSOL',
    telegram: '',
  },
  {
    coingeckoId: 'chex-token',
    symbol: 'CHEX',
    name: 'CHEX',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/10349/large/logo-white-bg-dark.png?1733475849',
    address: '6dKCoWjpj5MFU5gWDEFdpUUeBasBLK3wLEwhUzQPAa1e',
    pairAddress: 'D8JjVpFdXjFvHmsX7LyFy8iHXEqzhbQo576Rt8rZkyiq',
    website: 'https://chintai.io/',
    x: 'https://twitter.com/ChintaiNexus',
    telegram: 'https://t.me/chex_token',
  },
  {
    coingeckoId: 'ordinals',
    symbol: 'ordi',
    name: 'ORDI',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/30162/large/ordi.png?1696529082',
    address: 'u9nmK5sQovm6ACVCQbbq8xUMpFqdPSYxdxVwXUX4sjY',
  },
  {
    coingeckoId: 'popcat',
    symbol: 'POPCAT',
    name: 'Popcat',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/33760/large/image.jpg?1702964227',
    address: '7GCihgDB8fe6KNjn2MYtkzZcRjQy3t9GHdC8uHYmW2hr',
    pairAddress: 'FRhB8L7Y9Qq41qZXYLtC2nw8An1RJfLLxRF2x9RwLLMo',
    website: 'https://www.popcatsolana.xyz/',
    x: 'https://twitter.com/POPCATSOLANA/',
    telegram: 'https://t.me/popcatsolana',
  },
  {
    coingeckoId: 'basic-attention-token',
    symbol: 'BAT',
    name: 'Basic Attention Token (Wormhole)',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/677/large/basic-attention-token.png?1696501867',
    address: 'EPeUFDgHRxs9xxEPVaL6kfGQvCon7jmAWKVUHuux1Tpz',
    pairAddress: 'GYuh9af5UqUjzpU6tLFmwkg4P5DWU45pTSMoHEuZwzK8',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'baby-doge-coin',
    symbol: 'BabyDoge',
    name: 'Baby Doge Coin',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/16125/large/babydoge.jpg?1696515731',
    address: '7dUKUopcNWW6CcU4eRxCHh1uiMh32zDrmGf6ufqhxann',
    pairAddress: '8ssUoNgsmob23argRdQayyMJbvy41hZxwzvXnviFnSvU',
    website: 'https://babydoge.com',
    x: 'https://twitter.com/babydogecoin',
    telegram: 'https://t.me/babydogecoin',
  },
  {
    coingeckoId: 'aethir',
    symbol: 'ATH',
    name: 'Aethir Token',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/36179/large/logogram_circle_dark_green_vb_green_%281%29.png?1718232706',
    address: 'Dm5BxyMetG3Aq5PaG1BrG7rBYqEMtnkjvPNMExfacVk7',
    pairAddress: 'CGNenRRxcdtXm8qX9Bp2SevtUX1anXB4xBwA6Q1vJJPw',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'cat-in-a-dogs-world',
    symbol: 'MEW',
    name: 'cat in a dogs world',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/36440/large/MEW.png?1711442286',
    address: 'MEW1gQWJ3nEXg2qgERiKu7FAFj79PHvQVREQUzScPP5',
    pairAddress: '879F697iuDJGMevRkRcnW21fcXiAeLJK1ffsw2ATebce',
    website: 'https://mew.xyz/',
    x: 'https://twitter.com/MewsWorld',
    telegram: 'https://t.me/mewsworld',
  },
  {
    coingeckoId: 'ai-rig-complex',
    symbol: 'arc',
    name: 'AI Rig Complex',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/52701/large/u312bPNA_400x400.jpg?1734044765',
    address: '61V8vBaqAGMpgDQi4JcAwo1dmBGHsyhzodcPqnEVpump',
    pairAddress: '57mP5WoNrg3uiGFUdoeYr2CPUZak1L2ZgFtyFwoT7K6G',
    website: 'https://www.arc.fun/',
    x: 'https://x.com/arcdotfun',
    telegram: 'https://t.me/arcfunportal',
  },
  {
    coingeckoId: 'woo-network',
    symbol: 'WOO',
    name: 'WOO',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/12921/large/WOO_Logos_2023_Profile_Pic_WOO.png?1696512709',
    address: 'Dz8VutERqbHR2aFL5A3s1Ky4dG1unJT1jUFXXPaY9ytX',
    pairAddress: 'GjJiY7bTfTW8wT4X1PBxH6LBq4gNeWd6XUezdY5RYneh',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'act-i-the-ai-prophecy',
    symbol: 'ACT',
    name: 'Act I : The AI Prophecy',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/50984/large/ai_prophecy.jpg?1729653897',
    address: 'GJAFwWjJ3vnTsrQVabjBVK2TYB1YtRCQXRDfDgUnpump',
    pairAddress: 'B4PHSkL6CeZbxVqm1aUPQuVpc5ERFcaZj7u9dhtphmVX',
    website: 'https://actsol.xyz/',
    x: 'https://x.com/ACTICOMMUNITY',
    telegram: 'https://t.me/actportal',
  },
  {
    coingeckoId: 'bio-protocol',
    symbol: 'BIO',
    name: 'BIO',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/53022/large/bio.jpg?1735011002',
    address: 'bioJ9JTqW62MLz7UKHU69gtKhPpGi1BQhccj2kmSvUJ',
    pairAddress: '4LuGwek6Jv4xpGvsQwZXonmLuRhrpHtmKVs95bN9EkTm',
    website: 'https://www.bio.xyz/',
    x: 'https://x.com/bioprotocol',
    telegram: 'https://t.me/bio_protocol',
  },
  {
    coingeckoId: 'peanut-the-squirrel',
    symbol: 'Pnut ',
    name: 'Peanut the Squirrel ',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/51301/large/Peanut_the_Squirrel.png?1734941241',
    address: '2qEHjDLDLbuBgRYvsxhc5D6uDWAivNFZGan56P1tpump',
    pairAddress: '4AZRPNEfCJ7iw28rJu5aUyeQhYcvdcNm8cswyL51AY9i',
    website: 'https://www.pnutsol.com/',
    x: 'https://x.com/pnutsolana',
    telegram: 'https://t.me/pnutportal',
  },
  {
    coingeckoId: 'threshold-network-token',
    symbol: 't',
    name: 'Threshold Network',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/22228/large/nFPNiSbL_400x400.jpg?1696521570',
    address: '4Njvi3928U3figEF5tf8xvjLC5GqUN33oe4XTJNe7xXC',
  },
  {
    coingeckoId: 'swissborg',
    symbol: 'BORG',
    name: 'SwissBorg Token',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/2117/large/YJUrRy7r_400x400.png?1696503083',
    address: '3dQTr7ror2QPKQ3GbBCokJUmjErGg8kTJzdnYjNfvi3Z',
    pairAddress: 'KLkoFSdCpC523EmmGyJxmLv1A3itv8ZNiMZwjPmFXuk',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'drift-protocol',
    symbol: 'DRIFT',
    name: 'Drift',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/37509/large/DRIFT.png?1715842607',
    address: 'DriFtupJYLTosbwoN8koMbEYSx54aFAVLddWsbksjwg7',
    pairAddress: 'ESkg5Jjd9b5iCg7GfHT3LrcYtxQ7saCctznpncG4wxuL',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'gigachad-2',
    symbol: 'GIGA',
    name: 'GIGACHAD',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/34755/large/IMG_0015.png?1705957165',
    address: '63LfDmNb3MQ8mw9MtZ2To9bEA2M71kZUUGq5tiJxcqj9',
    pairAddress: '4xxM4cdb6MEsCxM52xvYqkNbzvdeWWsPDZrBcTqVGUar',
    website: 'https://linktr.ee/gigachadlinks',
    x: 'https://x.com/GIGACHAD_meme',
    telegram: 'https://t.me/GigaChadSol',
  },
  {
    coingeckoId: 'magic-eden',
    symbol: 'ME',
    name: 'Magic Eden',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/39850/large/_ME_Profile_Dark_2x.png?1734013082',
    address: 'MEFNBXixkEbait3xn9bkm8WsJzXtVsaJEn4c8Sam21u',
    pairAddress: '82pU8g2jQDyDfuH5nmCgFANS4vKTv6tPXe4WBDHRRyWh',
    website: 'https://mefoundation.com/',
    x: 'https://x.com/mefndn',
    telegram: '',
  },
  {
    coingeckoId: 'metaplex',
    symbol: 'MPLX',
    name: 'Metaplex Token',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/27344/large/mplx.png?1696526391',
    address: 'METAewgxyPbgwsseH8T16a39CQ5VyVxZi9zXiDPY18m',
    pairAddress: 'GExy9FLjGXMLRxNr4MMYFKG6dwXbepidB7oELNpopcRD',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'io',
    symbol: 'IO',
    name: 'IO',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/37754/large/io_blackbg.png?1715446363',
    address: 'BZLbGTNCSFfoth2GYDtwr7e4imWzpR5jqcUuGEwr646K',
    pairAddress: '67q6kZD6PD29pCvPhMkYSdT6MXJqmkCjeaVNfSYLZ2F2',
    website: 'https://io.net',
    x: 'https://x.com/ionet',
    telegram: '',
  },
  {
    coingeckoId: 'solayer',
    symbol: 'LAYER',
    name: 'Solayer',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/53498/large/Layer_320x320.png?1737481230',
    address: 'LAYER4xPpTCb3QL8S9u41EAhAX7mhBn8Q6xMTwY2Yzc',
    pairAddress: 'G6drsaPCR3pxsEmSTAc81kW1EL3kFAFwtSAkzUZXmgH3',
    website: 'https://solayer.org/',
    x: 'https://x.com/solayer_labs',
    telegram: '',
  },
  {
    coingeckoId: 'aixbt',
    symbol: 'AIXBT',
    name: 'aixbt by Virtuals (Wormhole)',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/51784/large/3.png?1731981138',
    address: '14zP2ToQ79XWvc7FQpm4bRnp9d6Mp1rFfsUW3gpLcRX',
    pairAddress: 'EekjuLbDZmmKvPqHL6u6p439ynJZim3yJKfL1CosREwk',
    website: 'https://aixbt.tech',
    x: 'https://x.com/aixbt_agent',
    telegram: 'https://t.me/aixbtportal',
  },
  {
    coingeckoId: 'hivemapper',
    symbol: 'HONEY',
    name: 'HONEY',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/28388/large/honey.png?1696527388',
    address: '4vMsoUT2BWatFweudnQM1xedRLfJgJ7hswhcpz4xgBTy',
    pairAddress: 'ENYEHSyduTbFN1xoSEGaLu7c1F8AqKucdscMuV5Yypy2',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'stepn',
    symbol: 'GMT',
    name: 'GMT',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/23597/large/token-gmt-200x200.png?1703153841',
    address: '7i5KKsX2weiTkry7jA4ZwSuXGhs5eJBEjY8vVxR4pfRx',
    pairAddress: '7PNQ9rfSGCbCC3XTeL6CwwAzevqQGvKXeXMxP2TjS7rM',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'm2-global-wealth-limited-mmx',
    symbol: 'MMX',
    name: 'M2 Global Wealth Limi (Wormhole)',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/33161/large/mmx.png?1700830276',
    address: '8bd3PSBp15xbjjCJzEJDrQDPiBTXgAJtgoxTcmXxytWL',
    pairAddress: 'Fpa2zCMAyWhpTn3JuA1ksUdSUDj6k9qqbxEbAxfFjE9z',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'frax-share',
    symbol: 'fxs',
    name: 'Frax Share',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/13423/large/Frax_Shares_icon.png?1696513183',
    address: '6LX8BhMQ4Sy2otmAWj7Y5sKd9YTVVUgfMsBzT6B9W7ct',
  },
  {
    coingeckoId: 'zignaly',
    symbol: 'ZIG',
    name: 'ZigCoin (Wormhole)',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/14796/large/zig.jpg?1731990265',
    address: '26f12PmBk77wQV1TzLe8XKkNBvMFggbuypxdtMLzNLzz',
    pairAddress: '4uLkkzTMthC3y4aajmHbY9WRDmdxXkebhpgCnokV9huV',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'melania-meme',
    symbol: 'MELANIA',
    name: 'Melania Meme',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/53775/large/melania-meme.png?1737329885',
    address: 'FUAfBo2jgks6gB4Z4LfZkqSZgzNucisEHqnNebaRxM1P',
    pairAddress: '3qhdX4gRWJabvcTLSw8UKrqHENF1ZVeXegQnrada6B5B',
    website: 'https://melaniameme.com/',
    x: 'https://x.com/MELANIATRUMP/status/1881087523847593995',
    telegram: '',
  },
  {
    coingeckoId: 'book-of-meme',
    symbol: 'BOME',
    name: 'BOOK OF MEME',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/36071/large/bome.png?1710407255',
    address: 'ukHH6c7mMyiWCf1b9pnWe25TSpkDDt3H5pQZgZ74J82',
    pairAddress: 'DSUvc5qf5LJHHV5e2tD184ixotSnCnwj7i4jJa4Xsrmt',
    website: '',
    x: 'https://twitter.com/Darkfarms1',
    telegram: 'https://t.me/BOOK_OF_MEME',
  },
  {
    coingeckoId: 'tensor',
    symbol: 'TNSR',
    name: 'Tensor',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/35972/large/tnsr.png?1712687367',
    address: 'TNSRxcUxoT9xBG3de7PiJyTDYu7kskLqcpddxnEJAS6',
    pairAddress: 'EZwNTDiGdT1W56wXWvU5NH2PUSJ21bPmQrRuzTmPyibu',
    website: 'https://tensor.foundation/',
    x: 'https://x.com/TensorFdn',
    telegram: 'https://t.me/VectorTGBot',
  },
  {
    coingeckoId: 'zebec-network',
    symbol: 'ZBCN',
    name: 'Zebec Network',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/37052/large/zbcn.jpeg?1713168241',
    address: 'ZBCNpuD7YMXzTHB2fhGkGi78MNsHGLRXUhRewNRm9RU',
    pairAddress: '6Mo8W6b67brHWokLNeXPdfwH7B1ir3xYCGd4EcBen6eM',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'euro-coin',
    symbol: 'EURC',
    name: 'EURC',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/26045/large/euro.png?1696525125',
    address: 'HzwqbKZw8HxMN6bF2yFZNrht3c2iXXzpKcFu7uBEDKtr',
    pairAddress: '2zVV22uNWdJNmkXpj5vCrMzwHGBoJdsyV7qACh29sK1w',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'bonfida',
    symbol: 'FIDA',
    name: 'Bonfida',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/13395/large/bonfida.png?1696513157',
    address: 'EchesyfXePKdLtoiZSL8pBe8Myagyy8ZRqsACNCFGnvp',
    pairAddress: 'A73SMfz2Skp4PkQpDd1UrMiwaseazk5wKKAWKf96Dcys',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'uxd-protocol-token',
    symbol: 'UXP',
    name: 'UXP Governance Token',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/20319/large/UXP.jpg?1696519722',
    address: 'UXPhBoR3qG4UCiGNJfV7MqhHyFqKN68g45GoYvAeL2M',
    pairAddress: '6ph8hDVRAga6YHN8PX76QsduEDbNurXGRUSJArjSuGC1',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'zeus-network',
    symbol: 'ZEUS',
    name: 'ZEUS',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/36692/large/logo-v1.png?1712427948',
    address: 'ZEUS1aR7aX8DFFJf5QjWj2ftDDdNTroMNGo8YoQm3Gq',
    pairAddress: 'E5X7mWprg8pdAqBT5HJ1ehu4crAsgUkUX5MwCjuTusZU',
    website: 'https://zeusnetwork.xyz/',
    x: 'https://x.com/ZeusNetworkHQ',
    telegram: '',
  },
  {
    coingeckoId: 'delysium',
    symbol: 'AGI',
    name: 'AGI Token (Wormhole)',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/29299/large/AGI_logo_200.png?1696528251',
    address: '8bUbe1ujsM1G3JEbBWVVCXa2widmuPdKUB2rGKMYFw7R',
    pairAddress: 'BTL6Qcr2TVaqs8ZYEx7jEq6LTvx3opg3f9DM2nxHmpxD',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'bybit-staked-sol',
    symbol: 'bbSOL',
    name: 'BybitSOL',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/40095/large/400x400.png?1725628094',
    address: 'Bybit2vBJGhPF52GBdNaQfUJ6ZpThSgHBobjWZpLPb4B',
    pairAddress: 'Ez8xXXjH3UsoJc5mZCwBLzfifca6VfZBg1kaReLUFfkN',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'sonic-svm',
    symbol: 'SONIC',
    name: 'Sonic SVM',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/53061/large/Token.png?1735169618',
    address: 'SonicxvLud67EceaEzCLRnMTBqzYUUYNr93DBkBdDES',
    pairAddress: '26BQ9SdKYP6odaFeGQC3oaST724QPFLpVuWqpB7xL1US',
    website: 'https://info-sonic.app/',
    x: 'https://x.com/SonicSVM',
    telegram: '',
  },
  {
    coingeckoId: 'geodnet',
    symbol: 'GEOD',
    name: 'Geodnet Token',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/31608/large/Circular_White.png?1696530424',
    address: '7JA5eZdCzztSfQbJvS8aVVxMFfd81Rs9VvwnocV1mKHu',
    pairAddress: 'BkX9RSHoDJGkU7pbHiksv3DprdLM3KWGoDSfGN9cGJ5d',
    website: 'https://geodnet.com/',
    x: 'https://twitter.com/GEODNET_',
    telegram: 'https://t.me/geodnet',
  },
  {
    coingeckoId: 'fartboy',
    symbol: 'FARTBOY',
    name: 'FARTBOY',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/53829/large/91IYNhRrJBL._UF1000_1000_QL80_.jpg?1737555683',
    address: 'y1AZt42vceCmStjW4zetK3VoNarC1VxJ5iDjpiupump',
    pairAddress: 'DhHVd5s4hqBGnTkFztsK98WGPtYUJjpUCqNnWaNLWb4F',
    website: 'https://www.fartboysol.com/',
    x: 'https://x.com/fartboy_cto?s=21&t=robySq6xGllel6mL2mukTg',
    telegram: 'https://t.me/iamfartboy',
  },

  {
    coingeckoId: 'goatseus-maximus',
    symbol: 'GOAT',
    name: 'Goatseus Maximus',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/50717/large/GOAT_LOGO_NEW.jpg?1731292759',
    address: 'CzLSujWBLFsSjncfkh59rUFqvafWcY5tzedWJSuypump',
    pairAddress: '9Tb2ohu5P16BpBarqd3N27WnkF51Ukfs8Z1GzzLDxVZW',
    website: 'https://goatchan.xyz/',
    x: 'https://x.com/truth_terminal?s=21&t=vGsyxXKadHr8hUMHWu6Frg',
    telegram: 'https://t.me/GoatseusMaximusSolanaPortal',
  },
  {
    coingeckoId: 'kamino',
    symbol: 'KMNO',
    name: 'Kamino',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/35801/large/tP0Lcgwp_400x400.jpg?1709824189',
    address: 'KMNo3nJsBXfcpJTVhZcXLW7RmTwTt4GVFE7suUBo9sS',
    pairAddress: '3ndjN1nJVUKGrJBc1hhVpER6kWTZKHdyDrPyCJyX3CXK',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'orca',
    symbol: 'ORCA',
    name: 'Orca',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/17547/large/Orca_Logo.png?1696517083',
    address: 'orcaEKTdK7LKz57vaAYr9QeNsVEPfiu6QeMU1kektZE',
    pairAddress: 'Hxw77h9fEx598afiiZunwHaX3vYu9UskDk9EpPNZp1mG',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'heyanon',
    symbol: 'Anon',
    name: 'HeyAnon',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/52961/large/AAI__ANON_SQ_Wb_250x250.png?1740500195',
    address: '9McvH6w97oewLmPxqQEoHUAv3u5iYMyQ9AeZZhguYf1T',
    pairAddress: 'CHdh3h5HygUnyZqyUjFwGGmsWSHo6ABHDZfbeBMJpcPz',
    website: 'https://heyanon.ai/',
    x: 'https://x.com/HeyAnonai',
    telegram: 'https://t.me/realwagmi',
  },
  {
    coingeckoId: 'carv',
    symbol: 'carv',
    name: 'CARV',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/37689/large/CARV_%281%29.png?1728418485',
    address: 'AFJtnuqGMaj5jAo6Pwxo28r1f7XAXXTSA8q3rG3q8b4A',
  },
  {
    coingeckoId: 'nosana',
    symbol: 'NOS',
    name: 'Nosana',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/22553/large/POfb_I4u_400x400.jpg?1696521873',
    address: 'nosXBVoaCTtYdLvKY6Csb4AC8JCdQKKAaWYtx2ZMoo7',
    pairAddress: 'Cj7kD2VmzwSrwKBieuYYbjPEvr8gwhNi76KUESbGDNfF',
    website: 'https://nosana.io/',
    x: 'https://x.com/nosana_ai',
    telegram: 'https://t.me/NosanaCompute',
  },
  {
    coingeckoId: 'dogelon-mars',
    symbol: 'ELON',
    name: 'Dogelon (Wormhole)',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/14962/large/6GxcPRo3_400x400.jpg?1696514622',
    address: '7ZCm8WBN9aLa3o47SoYctU6iLdj7wkGG5SV2hE5CgtD5',
    pairAddress: 'CdEcZZrLpaxbyd4J7oTp3oKxmZq3xoce8Ej1JmRvwdee',
    website: 'http://dogelonmars.com',
    x: 'https://twitter.com/DogelonMars',
    telegram: 'https://t.me/DogelonMars',
  },
  {
    coingeckoId: 'o-intelligence-coin',
    symbol: 'OI',
    name: 'OI',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/54232/large/logo_black.png?1739088464',
    address: 'AKzAhPPLMH5NG35kGbgkwtrTLeGyVrfCtApjnvqAATcm',
    pairAddress: 'DP1zq8PVJa6haTNfZHVDtzi8oNkNnoBYhjf4YHUZ1XFj',
    website: 'https://o.xyz',
    x: 'https://x.com/o_fndn',
    telegram: 'https://t.me/oxyz',
  },
  {
    coingeckoId: 'coin98',
    symbol: 'c98',
    name: 'Coin98',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/17117/large/logo.png?1696516677',
    address: 'C98A4nkJXhpVZNAZdHUA95RpTF3T4whtQubL3YobiUX9',
  },
  {
    coingeckoId: 'fwog',
    symbol: 'FWOG',
    name: 'FWOG',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/39453/large/fwog.png?1722318442',
    address: 'A8C3xuqscfmyLrte3VmTqrAq8kgMASius9AFNANwpump',
    pairAddress: 'AB1eu2L1Jr3nfEft85AuD2zGksUbam1Kr8MR3uM2sjwt',
    website: 'https://itsafwog.com/',
    x: 'https://x.com/itsafwog',
    telegram: 'https://t.me/fwogportal',
  },
  {
    coingeckoId: 'access-protocol',
    symbol: 'ACS',
    name: 'Access Protocol',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/28747/large/dR4FovX4_400x400.jpg?1696527727',
    address: '5MAYDfq5yxtudAhtfyuMBuHZjgAbaS9tbEyEQYAhDS5y',
    pairAddress: 'Go1hKVCy6mJA5usvHNV74KjkexXG2AUporDMeda5icmb',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'autonolas',
    symbol: 'OLAS',
    name: 'Autonolas (Wormhole)',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/31099/large/OLAS-token.png?1696529930',
    address: 'Ez3nzG9ofodYCvEmw73XhQ87LWNYVRM2s7diB5tBZPyM',
    pairAddress: '5dMKUYJDsjZkAD3wiV3ViQkuq9pSmWQ5eAzcQLtDnUT3',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'solend',
    symbol: 'SLND',
    name: 'Solend',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/19573/large/logo.webp?1733979407',
    address: 'SLNDpmoWTVADgEdndyvWzroNL7zSi1dF9PC3xHGtPwp',
    pairAddress: '4sjRg9NZxnZDh6AXaBB7EKXaQxAxEfazTihxgLJU9F1k',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'ponke',
    symbol: 'PONKE',
    name: 'PONKE',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/33929/large/ponke.jpeg?1738897723',
    address: '5z3EqYQo9HiCEs3R84RCDMu2n7anpDMxRhdK8PSWmrRC',
    pairAddress: '5uTwG3y3F5cx4YkodgTjWEHDrX5HDKZ5bZZ72x8eQ6zE',
    website: 'https://www.ponke.xyz',
    x: 'https://x.com/ponkesol',
    telegram: 'https://t.me/ponkesol',
  },
  {
    coingeckoId: 'bitget-wallet-token',
    symbol: 'BWB',
    name: 'Bitget Wallet Token (Wormhole)',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/37767/large/bwb.png?1715480561',
    address: '6FVyLVhQsShWVUsCq2FJRr1MrECGShc3QxBwWtgiVFwK',
    pairAddress: '7BB5yYWvQogeZr13oLDPPhMhhFPdMLeiqrb4b5Zs9Sy6',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'tars-protocol',
    symbol: 'TAI',
    name: 'TARS AI',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/37538/large/image_6.png?1736608965',
    address: 'Hax9LTgsQkze1YFychnBLtFH8gYbQKtKfWKKg2SP6gdD',
    pairAddress: '99a2qtfLAxv9LVhKesjEawjKy8Pwb4cypC5ccuCB4VUS',
    website: 'https://tars.pro',
    x: 'https://x.com/tarsprotocol',
    telegram: 'https://t.me/tars_pro',
  },
  {
    coingeckoId: 'non-playable-coin',
    symbol: 'NPC',
    name: 'Non-Playable Coin (Wormhole)',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/31193/large/NPC_200x200.png?1696530021',
    address: 'BeGY8KqKxboEwRbJd1q9H2K829jS4Rc5dEyNMYXCbV5p',
    pairAddress: 'FAn5gzoJMYriKeCoJzLTCepE9Y36oN3CidoF4dmgFNh9',
    website: 'https://www.npc.com/',
    x: 'https://twitter.com/nonplayablecoin',
    telegram: 'https://t.me/nonplayablecoin',
  },
  {
    coingeckoId: 'simon-s-cat',
    symbol: 'CAT',
    name: "Simon's Cat",
    logoUrl:
      "https://coin-images.coingecko.com/coins/images/39765/large/Simon's_Cat_Logo.png?1724017505",
    address: '3joMReCCSESngJEpFLoKR2dNcChjSRCDtybQet5uSpse',
    pairAddress: 'AxPuePyTfJx3eMDtmtCMi3X3pAto2V74VeSJ9SCKgmY3',
    website: 'https://simons.cat/',
    x: 'https://x.com/SimonsCatMeme',
    telegram: 'https://t.me/SimonsCatWorld',
  },
  {
    coingeckoId: 'alethea-artificial-liquid-intelligence-token',
    symbol: 'ALI',
    name: 'Artificial Liquid Int (Wormhole)',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/22062/large/ALI-v2.webp?1728501978',
    address: '9wvorGtBJ8gyLorFTmwXWcymPoGVUBn6MRzHwFpCdCeC',
    pairAddress: '7i2kx1oNJkiKGDZ3qi6DAqJhryuijrP62aPsHn5xZqXk',
    website: 'https://www.aliagents.ai',
    x: 'https://twitter.com/real_alethea',
    telegram: '',
  },
  {
    coingeckoId: 'cortex-2',
    symbol: 'CX',
    name: 'Cortex',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/53285/large/CX_Round.png?1735994730',
    address: 'CortexFv3fRcLKTgACr7aLqckGh5eP7TP3z9JHoKqMc6',
    pairAddress: 'atk4fymf1mfosqn6qrimjoe1hsjpcfwpty1tkpe5ez6e',
    website: 'https://cortexprotocol.com/',
    x: 'https://x.com/Cortex_Protocol',
    telegram: 'https://t.me/cortexprotocolofficial',
  },
  {
    coingeckoId: 'swarms',
    symbol: 'swarms',
    name: 'swarms',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/52988/large/swarms.jpg?1734921510',
    address: '74SBV4zDXxTRgv1pEMoECskKBkZHc2yGPnc7GYVepump',
    pairAddress: 'HL4KFTfhZZMm7NGefszQxzJ3M6CaDWE7TesyuRuQYmMJ',
    website: 'https://docs.swarms.world/en/latest/',
    x: 'https://x.com/swarms_corp',
    telegram: '',
  },

  {
    coingeckoId: 'comedian',
    symbol: 'Ban',
    name: 'Comedian',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/51100/large/ban.jpg?1730085215',
    address: '9PR7nCP9DpcUotnDPVLUBUZKu5WAYkwrCUx9wDnSpump',
    pairAddress: 'DmAsjXoceoL5vTKZbYpTpXPo7MKm16FMfNMm3PJFiUha',
    website: 'https://banart.art/',
    x: 'https://x.com/rwa_ban?s=21',
    telegram: 'https://t.me/bansolgroup',
  },
  {
    coingeckoId: 'griffain',
    symbol: 'GRIFFAIN',
    name: 'test griffain.com',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/52547/large/aAp7HijF4Uf1SkZO3FsVMyrbBc5kux_0vIlI7Amxiu7ygza2T_Swtp8bA2KoL_yU0YWw7c52LG9wflD7b5KMZ6GNJgDtgQfmMKy75SBQ5ldIHl6qffC9SNWqKyvqKQJ5sWZgJnXztPPsuJD_IVTTdPlabPlxxuNq7OAxQcjCbRxnge3tim3QyyIrc5vTOzWR93BoZVf0pd7EzwziVlhzov.jpg?1733590142',
    address: 'KENJSUYLASHUMfHyy5o4Hp2FdNqZg1AsUPhfH2kYvEP',
    pairAddress: 'CpsMssqi3P9VMvNqxrdWVbSBCwyUHbGgNcrw7MorBq3g',
    website: 'https://griffain.com/',
    x: 'https://x.com/griffaindotcom',
    telegram: 'https://t.me/GriffainSOL',
  },
  {
    coingeckoId: 'smardex',
    symbol: 'SDEX',
    name: 'SmarDex Token (Wormhole)',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/29470/large/SDEX_logo_transparent_outside_240x240.png?1696930070',
    address: '9dzSzFvPsKDoY2gdWErsuz2H1o4tbzvgBhrNZ9cvkD2j',
    pairAddress: '9tpuSFaYmYEJ73SuaMwoMJBhfuQzpCia9SLVLir3D7tG',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'moo-deng',
    symbol: 'MOODENG',
    name: 'Moo Deng',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/50264/large/MOODENG.jpg?1726726975',
    address: 'ED5nyyWEzpPPiWimP8vYm7sD7TD3LAt3Q3gRTWHzPJBY',
    pairAddress: '22WrmyTj8x2TRVQen3fxxi2r4Rn6JDHWoMTpsSmn8RUd',
    website: 'https://www.moodengsol.com/',
    x: 'https://x.com/MooDengSOL',
    telegram: 'https://t.me/+hCTQLf149JNlZjgx',
  },
  {
    coingeckoId: 'pepecoin-2',
    symbol: 'pepecoin',
    name: 'pepeCoin (Wormhole)',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/30219/large/pepecoin-icon_200x200.png?1735790725',
    address: 'EXJvx3KksbWP9QmPmtRr8mkQXD2kZrFRENCJitMs1eZ6',
    pairAddress: 'FW48DtV8ENKrraBnCj7UMaS8EksuQmiSh4gDVG8HY8Ch',
    website: 'https://www.pepecoin.io/',
    x: 'https://x.com/pepecoins?s=21&t=jvHknmg1bMncBKHP-SA4NQ',
    telegram: 'https://t.me/pepecoins',
  },
  {
    coingeckoId: 'corgiai',
    symbol: 'CORGIAI',
    name: 'CorgiAI',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/30933/large/Token.png?1696529775',
    address: '79F32BvHBE49gPsvypYTGzcpWGvt66mgvenQow3mJjXu',
    pairAddress: '5Abc2LhMoRwTVCqrdzgQy6yteEJ3MZbYU5iT1jXHr7jb',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'oraichain-token',
    symbol: 'ORAI',
    name: 'Oraichain',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/12931/large/orai.png?1696512718',
    address: 'oraiyuR7hz6h7ApC56mb52CJjPZBB34USTjzaELoaPk',
    pairAddress: '2oTMLj5zCzYfApnPers4MwunRNF8QJuL5oQGeXKAKYgA',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'stonks-5',
    symbol: 'STONKS',
    name: 'STONKS',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/54302/large/548f883d-3219-47e8-944c-22ae77a106f1.jpg?1739167478',
    address: '6NcdiK8B5KK2DzKvzvCfqi8EHaEqu48fyEzC8Mm9pump',
    pairAddress: '5N96fYr2ZzaiNyZaYGAi31xvT5ExzfPnwh2s95yaXXSv',
    website: 'https://mystonks.org/',
    x: 'https://x.com/Stonks_DM',
    telegram: 'https://t.me/STONKS_Offical',
  },
  {
    coingeckoId: 'ava-ai',
    symbol: 'AVA',
    name: 'Ava AI',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/51935/large/7VZQ0qhB_400x400_%282%29.jpg?1732206907',
    address: 'DKu9kykSfbN5LBfFXtNNDPaX35o4Fv6vJ9FKk7pZpump',
    pairAddress: 'GjvW8JQSpKG5ogjyD3zozfaeJSShTajS5ZFrexT8L12k',
    website: 'https://www.holoworld.com/',
    x: 'https://x.com/AVA_holo',
    telegram: 'https://t.me/AvaAIonSol',
  },
  {
    coingeckoId: 'jambo',
    symbol: 'J',
    name: 'Jambo',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/53539/large/2D.png?1736596215',
    address: 'Jambjx1oJoZNBZiqbiF9TqgatEZPdyfvYa9WVsKNzUh',
    pairAddress: 'DkXPwET3qYwQtUAxJwnu7onECBrbywbdWVLMbaBF9Q2u',
    website: 'https://www.jambo.technology/',
    x: 'https://x.com/JamboTechnology',
    telegram: 'https://t.me/jambotechnology',
  },
  {
    coingeckoId: 'unicorn-fart-dust',
    symbol: 'UFD',
    name: 'Unicorn Fart Dust',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/52931/large/untitled.png?1734708671',
    address: 'eL5fUxj2J4CiQsmW85k5FG9DvuQjjUoBHoQBi2Kpump',
    pairAddress: '78sBWyimVhLumzZg1bdMD6ogGig8QpmgYZqCXNyMxx4z',
    website: 'https://www.youtube.com/@ronsbasement',
    x: 'https://x.com/BasementRon',
    telegram: 'https://t.me/UFD_Announcements',
  },
  {
    coingeckoId: 'sweatcoin',
    symbol: 'sweat',
    name: 'Sweat Economy',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/25057/large/fhD9Xs16_400x400.jpg?1696524208',
    address: 'NSG17kiSApMumWjLbZ4BLx8biPaAxTk9tDCdy1Fb9ia',
  },
  {
    coingeckoId: 'tajir-tech-hub',
    symbol: 'TJRM',
    name: 'Tajir Media',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/53685/large/3D_logo_PG.png?1737027049',
    address: '4AdDFsG1xzz1L7zKGo2fbiqv256Z92u8uCcJCgYuTBLo',
    pairAddress: '25VqtLDZHTGrfLr4rTWV1nHHwYnAHx34Hcko5Z821q6n',
    website: 'https://www.tajirtechhub.com/',
    x: 'https://x.com/tajirtechhub?s=21',
    telegram: 'https://t.me/TajirMedia_EN',
  },
  {
    coingeckoId: 'dao-maker',
    symbol: 'DAO',
    name: 'DAO Maker (Wormhole)',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/13915/large/4.jpg?1727532864',
    address: '85aM5XJhdDeUw4MbGKM56zmWnsRyh76zUVut97uPjiCg',
    pairAddress: '2qY19HB2FjkHV1JeQ6obWUC1Wpf5mw35jXD96x8VqvmD',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'vine',
    symbol: 'VINE',
    name: 'Vine Coin',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/53859/large/vine.jpg?1737613523',
    address: '6AJcP7wuLwmRYLBNbi825wgguaPsWzPBEHcHndpRpump',
    pairAddress: '58fzJMbX5PatnfJPqWWsqkVFPRKptkbb5r2vCw4Qq3z9',
    website: 'https://www.vineco.in/',
    x: 'https://x.com/rus',
    telegram: 'http://t.me/vinecoinrus',
  },
  {
    coingeckoId: 'limitus',
    symbol: 'LMT',
    name: 'LIMITUS',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/52887/large/LIMITUS.jpg?1734600718',
    address: '86t88w3MKT38HChTBKBwEeb1RW1MeTceaW68qY2Vpump',
    pairAddress: '38256B3SrJ8NTd4q9HgJjowGmSVw357f457Wqf5HS8h7',
    website: 'https://www.limitus.ai/',
    x: 'https://x.com/LimitusIntel',
    telegram: '',
  },
  {
    coingeckoId: 'helium-mobile',
    symbol: 'MOBILE',
    name: 'Helium Mobile',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/29879/large/Mobile_Icon.png?1696528804',
    address: 'mb1eu7TzEc71KxDpsmsKoucSSuuoGLv1drys1oP2jh6',
    pairAddress: '45zpzzpZquaVv4BAdXfzNbuba7DAXV32d1sTrUh5wcnW',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'mcdull',
    symbol: 'MCDULL',
    name: 'McDull',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/51176/large/LNPFe2mY_400x400.jpg?1730297902',
    address: 'Buoj8HCZMnLRwzDmjzaswhkVhLZD58PG4pZ7rnYp6pCr',
    pairAddress: 'CdpkQzoK4iS6TVYsm2Nbyb6tZc1piJHKfLcWKwcgYX9L',
    website: 'https://mcdull.io/',
    x: 'https://x.com/mcdull_io',
    telegram: 'https://t.me/mcdull_io',
  },
  {
    coingeckoId: 'debridge',
    symbol: 'DBR',
    name: 'deBridge',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/38019/large/DBR_icon_Color.png?1724708885',
    address: 'DBRiDgJAMsM95moTzJs7M9LnkGErpbv9v6CUR1DXnUu5',
    pairAddress: 'E5H5BXLranyJFHEzvR3R2j6kGDQ3Fnx8sPKSsgYqyya8',
    website: 'https://debridge.finance/',
    x: '',
    telegram: 'https://t.me/+qx3n5TVp__c5MzAx',
  },
  {
    coingeckoId: 'zerebro',
    symbol: 'ZEREBRO',
    name: 'zerebro',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/51289/large/zerebro_2.png?1730588883',
    address: '8x5VqbHA8D7NkD52uNuS5nnt3PwA8pLD34ymskeSo2Wn',
    pairAddress: '3sjNoCnkkhWPVXYGDtem8rCciHSGc9jSFZuUAzKbvRVp',
    website: 'https://zerebro.org/',
    x: 'https://x.com/0xzerebro',
    telegram: 'https://t.me/zerebro_portal',
  },
  {
    coingeckoId: 'bc-token',
    symbol: 'BC',
    name: 'BCGame Coin',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/53197/large/Icon_%281%29.png?1735616292',
    address: 'BCNT4t3rv5Hva8RnUtJUJLnxzeFAabcYp8CghC1SmWin',
    pairAddress: 'E8TRsCYBVaB4GD4Nx3F8SGpH3KMYTADR1EkdQC2EJFGK',
    website: 'https://bc.game',
    x: 'https://x.com/bcgamecoin',
    telegram: 'https://t.me/official_bc_token',
  },
  {
    coingeckoId: 'big-dog-fink',
    symbol: 'BINK',
    name: 'Big Dog Fink',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/51674/large/IMG_6585.png?1731774784',
    address: 'CeK6k4BMmiqkxkzYAbQuUp3hrVFSHxuQ1LJXmNybc3vz',
    pairAddress: '9Ah4ZpVRZdb2SeiLNbavAyLbAq3xXwKg6fmnLRSZ9FTM',
    website: 'https://bigdogfink.com/',
    x: 'https://x.com/bigdogfink',
    telegram: 'https://t.me/bigdogfink',
  },

  {
    coingeckoId: 'alchemist-ai',
    symbol: 'ALCH',
    name: 'Alchemist AI',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/52302/large/small-logo.png?1733053544',
    address: 'HNg5PYJmtqcmzXrv6S9zP1CDKk5BgDuyFBxbvNApump',
    pairAddress: 'FyDF3vKQFbcvNTsBi7L7LremrFPmXKbQqgAgnPg1hXXd',
    website: 'https://www.alchemistai.app/',
    x: 'https://x.com/alchemistAIapp',
    telegram: '',
  },
  {
    coingeckoId: 'neon',
    symbol: 'NEON',
    name: 'Neon EVM Token',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/28331/large/neon_%281%29.png?1696527338',
    address: 'NeonTjSjsuo3rexg9o6vHuMXw62f9V7zvmu8M8Zut44',
    pairAddress: 'GUWM1arUyDnkMGCHvJu3yt1qomJ988utqC3dFN2AUCDT',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'marinade',
    symbol: 'MNDE',
    name: 'Marinade',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/18867/large/MNDE.png?1696518327',
    address: 'MNDEFzGvMt87ueuHvVU9VcTqsAP5b3fTGPsHuuPA5ey',
    pairAddress: 'BVXNG6BrL2Tn3NmppnMeXHjBHTaQSnSnLE99JKwZSWPg',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'saros-finance',
    symbol: 'saros',
    name: 'Saros',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/34594/large/saros-token-logo.png?1705476813',
    address: 'SarosY6Vscao718M4A778z4CGtvcwcGef5M9MEH1LGL',
  },
  {
    coingeckoId: 'pain',
    symbol: 'PAIN',
    name: 'PAIN',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/54493/large/pain.jpg?1740020794',
    address: '1Qf8gESP4i6CFNWerUSDdLKJ9U1LpqTYvjJ2MM4pain',
    pairAddress: 'CopraAQegh7HohkLgYayjoRENXsf66eYaDtwFpbr8zRZ',
    website: 'https://paintoken.com/',
    x: 'https://x.com/pain',
    telegram: '',
  },
  {
    coingeckoId: 'deapcoin',
    symbol: 'dep',
    name: 'DEAPCOIN',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/10970/large/DEAPcoin_01.png?1696510917',
    address: 'BgwQjVNMWvt2d8CN51CsbniwRWyZ9H9HfHkEsvikeVuZ',
  },
  {
    coingeckoId: 'chill-guy',
    symbol: 'CHILLGUY',
    name: 'Just a chill guy',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/51746/large/Scherm%C2%ADafbeelding_2024-11-15_om_20.57.58.png?1731926037',
    address: 'Df6yfrKC8kZE3KNkrHERKzAetSxbrWeniQfyJY4Jpump',
    pairAddress: '93tjgwff5Ac5ThyMi8C4WejVVQq4tuMeMuYW1LEYZ7bu',
    website: '',
    x: 'https://x.com/chillguycto',
    telegram: 'https://t.me/chillguycto',
  },
  {
    coingeckoId: 'genesysgo-shadow',
    symbol: 'SHDW',
    name: 'Shadow Token',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/22271/large/Property_1_Color.png?1696521615',
    address: 'SHDWyBxihqiCj6YekG2GUr7wqKLeLAMK1gHZck9pL6y',
    pairAddress: '25bQ6UzZpgFgnU7MqZdqM9Axi6oJunytRL2LgXruDWZB',
    website: 'https://genesysgo.com/',
    x: 'https://twitter.com/genesysgo',
    telegram: '',
  },
  {
    coingeckoId: 'concierge-io',
    symbol: 'AVA',
    name: 'AVA (Wormhole)',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/3014/large/AVA_Logo_160x160px_Black.png?1696503750',
    address: 'G8LfyGVsjsLzetJ5RWZVAhMo4H9cb58ET1Z6gEZJQdPM',
    pairAddress: 'ATEQDF6jZwBfqy5jYzLEfjMNxzdk9k32XDmVFjGZEBsc',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'orderly-network',
    symbol: 'ORDER',
    name: 'Orderly Network',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/38501/large/Orderly_Network_Coingecko_200*200.png?1717751359',
    address: 'ABt79MkRXUsoHuV2CVQT32YMXQhTparKFjmidQxgiQ6E',
    pairAddress: 'BxUigngqxhU8Wapwvck5cavcBbfgE47ETNwLeXnCVwz4',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'slerf',
    symbol: 'SLERF',
    name: 'SLERF',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/36178/large/slerf.jpeg?1710753228',
    address: '7BgBvyjrZX1YKz4oh9mjb8ZScatkkwb8DzFx7LoiVkM3',
    pairAddress: 'AgFnRLUScRD2E4nWQxW73hdbSN7eKEUb2jHX7tx9YTYc',
    website: 'https://www.slerf.wtf/',
    x: 'https://twitter.com/Slerfsol',
    telegram: 'https://t.me/slerfthesloth',
  },
  {
    coingeckoId: 'daddy-tate',
    symbol: 'DADDY',
    name: 'DADDY TATE',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/38684/large/DADDY_TATE.png?1718336003',
    address: '4Cnk9EPnW5ixfLZatCPJjDB1PUtcRpVVgTQukm9epump',
    pairAddress: 'zcdAw3jpcqEY8JYVxNVMqs2cU35cyDdy4ot7V8edNhz',
    website: 'https://www.cobratate.com/',
    x: 'https://x.com/i/communities/1855296591726604541',
    telegram: 'https://t.me/DADDYTATECTO',
  },
  {
    coingeckoId: 'math',
    symbol: 'math',
    name: 'MATH',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/11335/large/2020-05-19-token-200.png?1696511257',
    address: 'CaGa7pddFXS65Gznqwp42kBhkJQdceoFVT7AQYo8Jr8Q',
  },
  {
    coingeckoId: 'osol',
    symbol: 'OI',
    name: 'OI',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/53195/large/osol_logo_200x.png?1735602170',
    address: '2otVNpcHXn9MKeDk3Zby5uanF3s7tki4toaJ3PZcXaUd',
    pairAddress: 'DP1zq8PVJa6haTNfZHVDtzi8oNkNnoBYhjf4YHUZ1XFj',
    website: 'https://o.xyz',
    x: 'https://x.com/o_fndn',
    telegram: 'https://t.me/oxyz',
  },
  {
    coingeckoId: 'libra-5',
    symbol: 'LIBRA',
    name: 'LIBRA',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/54433/large/libra-logo.png?1739612550',
    address: 'Bo9jh3wsmcC2AjakLWzNmKJ3SgtZmXEcSaW7L2FAvUsU',
    pairAddress: 'BzzMNvfm7T6zSGFeLXzERmRxfKaNLdo4fSzvsisxcSzz',
    website: '',
    x: 'https://x.com/JMilei/status/1890521742961156552',
    telegram: '',
  },
  {
    coingeckoId: 'dego-finance',
    symbol: 'dego',
    name: 'Dego Finance',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/12503/large/Token.png?1733381203',
    address: 'BU4eP1vCR99amXKsMXhctX8YpqUa7wbULQ26XaQbazkS',
  },
  {
    coingeckoId: 'parcl',
    symbol: 'PRCL',
    name: 'Parcl',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/37078/large/ParclToken.png?1737478326',
    address: '4LLbsb5ReP3yEtYzmXewyGjcir5uXtKFURtaEUVC2AHs',
    pairAddress: 'BWGP8CqKgg1rV6kYNFnbGbSYXxnYah4BQg1Sw1Nqy7hm',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'bitrise-token',
    symbol: 'BRISE',
    name: 'Bitgert',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/17388/large/200x200.png?1696516937',
    address: 'ErSZNwsamWjR9Hj2o18GLwVyTkooyGbdptjMjuv72X8A',
    pairAddress: '7M8d1TxydTADm3QRUEJjpDELj3djKp6qQ4pHtyU9Lv1T',
    website: '',
    x: '',
    telegram: '',
  },

  {
    coingeckoId: 'pippin',
    symbol: 'pippin',
    name: 'Pippin',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/51589/large/pippin_logo.png?1731570163',
    address: 'Dfh5DzRgSvvCFDoYc2ciTkMrbDfRKybA4SoFbPmApump',
    pairAddress: '8WwcNqdZjCY5Pt7AkhupAFknV2txca9sq6YBkGzLbvdt',
    website: 'https://www.yohei.me/',
    x: 'https://x.com/pippinlovesyou',
    telegram: 'https://t.me/PippinPortal',
  },
  {
    coingeckoId: 'swarmnode-ai',
    symbol: 'SNAI',
    name: 'SwarmNode.ai',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/52972/large/S_%28200_x_200_px%29.png?1734883975',
    address: 'Hjw6bEcHtbHGpQr8onG3izfJY5DJiWdt7uk2BfdSpump',
    pairAddress: '9qiKN1QnuUVtZXhRWo86Prnr3Lsm933MvJ8phrt5ah8Y',
    website: 'https://swarmnode.ai/',
    x: 'https://x.com/swarmnode',
    telegram: '',
  },
  {
    coingeckoId: 'layer3',
    symbol: 'L3',
    name: 'Layer3',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/37768/large/Square.png?1722045128',
    address: '5k84VjAKoGPXa7ias1BNgKUrX7e61eMPWhZDqsiD4Bpe',
    pairAddress: 'Dps9eL3mqqWqqz1JcUdVpxo6EQEdbH9fBxex2mDrhBf1',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'meta-2',
    symbol: 'META',
    name: 'META',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/35393/large/8cwEAxSLrrLFuxpeH7L8cKyCLM7TqvTxQOV59Mrp0_Q.png?1708453400',
    address: 'METADDFL6wWMWEoKTFJwcThTbUmtarRJZjRpzUvkxhr',
    pairAddress: '6dyEn3YXFkVzN5EKKJhQML8LXKFczQ8uY5cnsmqTTZo1',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'pocket-network',
    symbol: 'POKT',
    name: 'Pocket Network (Wormhole)',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/22506/large/POKT.jpg?1703257310',
    address: '6CAsXfiCXZfP8APCG6Vma2DFMindopxiqYQN4LSQfhoC',
    pairAddress: '5qJCeYWzvkrKuD1r7bQDus8ffm2vjrunxNUht6NTeise',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'star-atlas',
    symbol: 'ATLAS',
    name: 'Star Atlas',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/17659/large/Icon_Reverse.png?1696517190',
    address: 'ATLASXmbPQxBUYbxPsV97usA3fPQYEqzQBUHgiFCUsXx',
    pairAddress: 'F73euqPynBwrgcZn3fNSEneSnYasDQohPM5aZazW9hp2',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'crown-by-third-time-games',
    symbol: 'CROWN',
    name: 'CROWN Token',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/30452/large/crown_200_transparent.png?1696529338',
    address: 'GDfnEsia2WLAW5t8yx2X5j2mkfA74i5kwGdDuZHt7XmG',
    pairAddress: 'GgvEV7WiEM9t7xobkBUw54x5XSXZH9mZ1vf43hCmrVyX',
    website: 'https://photofinish.live',
    x: 'https://twitter.com/photofinishgame',
    telegram: '',
  },
  {
    coingeckoId: 'houdini-swap',
    symbol: 'LOCK',
    name: 'Houdini Swap',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/35132/large/LOCK_Logo.png?1707443455',
    address: 'App2Sp9pgmQG7yD6uVaygULxALf4TpfALgnhHEkJimih',
    pairAddress: '6wjXjxZuoXrnhtu494XuzH9seJHU9caeyewqLJEe1dSp',
    website: 'https://houdiniswap.com/',
    x: 'https://x.com/HoudiniSwap',
    telegram: 'https://t.me/houdiniswap',
  },
  {
    coingeckoId: 'elon4afd',
    symbol: 'Elon4AfD',
    name: 'Elon for AfD ',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/53992/large/ElonNewLogo200.jpeg?1737884581',
    address: 'BkYAUVMar1gLwuFLv2n5cmB6HhcNtvd86kU3gqAypump',
    pairAddress: 'H6QKN2x9bCP27auuAWB4RKE9T2YjkMYXD3jWJWvKxZRV',
    website: 'https://elon4afd.meme',
    x: 'https://x.com/Elon4AfD',
    telegram: 'https://t.me/Elon4AfD',
  },
  {
    coingeckoId: 'richquack',
    symbol: 'quack',
    name: 'Rich Quack',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/16356/large/57198446-0-Get-Rich-Quick-Gober.png?1696515955',
    address: '9HGziACBczM3VorD3B6ZYtj6BA595jq8erzsSVtUNo6N',
  },
  {
    coingeckoId: 'star-atlas-dao',
    symbol: 'POLIS',
    name: 'Star Atlas DAO',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/17789/large/POLIS.jpg?1696517312',
    address: 'poLisWXnNRwC6oBu1vHiuKQzFjGL4XDSu4g9qjz9qVk',
    pairAddress: '5tho4By9RsqTF1rbm9Akiepik3kZBT7ffUzGg8bL1mD',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'michicoin',
    symbol: '$michi',
    name: 'michi',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/37309/large/5mbK36SZ7J19An8jFochhQS4of8g6BwUjbeCSxBSoWdp.jpeg?1713952829',
    address: '5mbK36SZ7J19An8jFochhQS4of8g6BwUjbeCSxBSoWdp',
    pairAddress: 'GH8Ers4yzKR3UKDvgVu8cqJfGzU4cU62mTeg9bcJ7ug6',
    website: 'http://michisolana.org/',
    x: 'https://twitter.com/michionsolana',
    telegram: 'https://t.me/michiportal',
  },
  {
    coingeckoId: 'yne',
    symbol: 'YNE',
    name: 'yesnoerror',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/52985/large/yesnoerror.jpg?1734919313',
    address: '7D1iYWfhw2cr9yBZBFE6nZaaSUvXHqG5FizFFEZwpump',
    pairAddress: 'AAoREr9vexyGrinK6Z2GBcq5TKrNkZQXzkDpDDeXVaMk',
    website: 'https://yesnoerror.com',
    x: 'https://x.com/yesnoerror',
    telegram: 'https://t.me/yes_no_error',
  },
  {
    coingeckoId: 'artrade',
    symbol: 'ATR',
    name: 'Artrade Token',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/24894/large/ATR_logo.png?1706954201',
    address: 'ATRLuHph8dxnPny4WSNW7fxkhbeivBrtWbY6BfB4xpLj',
    pairAddress: '2Ky6BskrcKNCJSrP4X6bgrPPe1erBArBAhyZi2C8nPwy',
    website: 'https://artrade.app/',
    x: 'https://twitter.com/ArtradeApp',
    telegram: 'https://t.me/ArtradeEnglish',
  },
  {
    coingeckoId: 'portal-2',
    symbol: 'portal',
    name: 'Portal',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/35436/large/portal.jpeg?1708590254',
    address: 'FMQjDvT1GztVxdvYgMBEde4L54fftFGx9m5GmbqeJGM5',
  },
  {
    coingeckoId: 'strike-3',
    symbol: 'STRIKE',
    name: 'STRIKE',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/54170/large/STRIKE.jpg?1738560022',
    address: 'STrikemJEk2tFVYpg7SMo9nGPrnJ56fHnS1K7PV2fPw',
    pairAddress: 'BCXjm4FfSoquZQJV5Wcje1g1pSHW2hFMU9wDE98Nyatb',
    website: 'https://striketoken.io',
    x: 'https://x.com/striketoken_',
    telegram: '',
  },

  {
    coingeckoId: 'department-of-government-efficiency',
    symbol: 'DOGE',
    name: 'Department Of Governm (Wormhole)',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/39841/large/IMG_9775.PNG?1729771739',
    address: 'KQijDbNJ6rPCqhtXrfH6gKa5cH3a39At8vHq34nnPbF',
    pairAddress: '7ESTvPaxJGbfGTZgHtmKEfJxQYjNsKfyTaKK23CZnrLF',
    website: 'https://www.dogegov.com/',
    x: 'https://x.com/doge_eth_gov',
    telegram: 'https://t.me/NewDOGEonETH_CTO',
  },
  {
    coingeckoId: 'step-finance',
    symbol: 'STEP',
    name: 'Step',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/14988/large/step.png?1696514652',
    address: 'StepAscQoEioFxxWGnh2sLBDFp9d8rvKz2Yp39iDpyT',
    pairAddress: '4Sx1NLrQiK4b9FdLKe2DhQ9FHvRzJhzKN3LoD6BrEPnf',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'dogeai-2',
    symbol: 'DOGEAI',
    name: 'DOGE AI',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/53854/large/dogeai_pfp.jpg?1737610397',
    address: '9UYAYvVS2cZ3BndbsoG1ScJbjfwyEPGxjE79hh5ipump',
    pairAddress: '3d7PRDYq3CvRxFBoXrYeKr3DYYco2AnYupv9D9bAUoyH',
    website: 'https://dogeai.info/',
    x: 'https://x.com/dogeai_gov',
    telegram: '',
  },
  {
    coingeckoId: 'retardio',
    symbol: 'RETARDIO',
    name: 'RETARDIO',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/35759/large/RETARDIO_LOGO.png?1728587088',
    address: '6ogzHhzdrQr9Pgv6hZ2MNze7UrzBMAFyBBWUYp1Fhitx',
    pairAddress: '5eLRsN6qDQTQSBF8KdW4B8mVpeeAzHCCwaDptzMyszxH',
    website: 'https://retardio.xyz/',
    x: 'https://x.com/retardiolove',
    telegram: 'https://t.me/retardiosol',
  },
  {
    coingeckoId: 'memdex100',
    symbol: 'MEMDEX',
    name: 'MEMDEX100',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/53587/large/memdex.jpg?1738547908',
    address: '83iBDw3ZpxqJ3pEzrbttr9fGA57tttehDAxoFyR1moon',
    pairAddress: '7cjgE6PwoNqfXjayUvUDE7TCS2GmPNnP1jCT29jT3JVJ',
    website: 'https://memdex.live/',
    x: 'https://x.com/thememdex100',
    telegram: 'https://t.me/memdex100',
  },
  {
    coingeckoId: 'ninja-squad',
    symbol: 'NST',
    name: 'Ninja Squad Token (Wormhole)',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/22248/large/nst-logo-200x200.png?1711559985',
    address: 'G7iK3prSzAA4vzcJWvsLUEsdCqzR7PnMzJV61vSdFSNW',
    pairAddress: 'caWWda11Ye4Xme9D5GKo67Hb8g5mJv1SzKAwrLRnggQ',
    website: 'https://ninjatraders.io/',
    x: 'https://x.com/ninjasquadnft',
    telegram: 'https://t.me/ninjatraderstr',
  },
  {
    coingeckoId: 'rune-pups',
    symbol: 'PUPS',
    name: 'PUPS WORLD PEACE',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/37159/large/token_logo.png?1732383184',
    address: '2oGLxYuNBJRcepT1mEV6KnETaLD7Bf6qq3CM6skasBfe',
    pairAddress: 'FfQtSPNUSTDZwNBhJLgpVPG95ediXfeFnfZnoGPELKML',
    website: 'https://www.pupstoken.com/',
    x: 'https://twitter.com/PupsToken',
    telegram: 'https://t.me/pupsworldpeace',
  },
  {
    coingeckoId: 'mango-markets',
    symbol: 'MNGO',
    name: 'Mango',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/14773/large/token-mango.png?1696514442',
    address: 'MangoCzJ36AjZyKwVj3VnYU4GTonjfVEnJmvvWaxLac',
    pairAddress: '34tFULRrRwh4bMcBLPtJaNqqe5pVgGZACi5sR8Xz95KC',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'onyx-arches',
    symbol: 'oxa',
    name: 'Onyx Arches',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/53955/large/oxa_200.png?1737789579',
    address: '4ZfitzW524FUvWrGuNTg3x7d7cfCuNZzUaNEiB2BT5Lj',
  },
  {
    coingeckoId: 'purple-pepe',
    symbol: 'PURPE',
    name: 'Purple Pepe',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/38962/large/IMG_3953.jpeg?1719709952',
    address: 'HBoNJ5v8g71s2boRivrHnfSB5MVPLDHHyVjruPfhGkvL',
    pairAddress: 'CpoYFgaNA6MJRuJSGeXu9mPdghmtwd5RvYesgej4Zofj',
    website: 'https://www.purpe.xyz/',
    x: 'https://x.com/PurplePepeS0L',
    telegram: 'https://t.me/Purpe_SOL',
  },
  {
    coingeckoId: 'ox-fun',
    symbol: 'OX',
    name: 'OX',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/35365/large/9.png?1727331352',
    address: '3E2z4KX7y457xJqK9RQeJhA29oPdoUvAAD3Ea3zQyuG3',
    pairAddress: 'AyDkGesGgANNKp6aYLQZeSoNZFuZyUwDcUQqiEpyXVCZ',
    website: 'https://ox.fun',
    x: 'https://x.com/OXFUNHQ',
    telegram: 'https://t.me/OXFUNPORTAL',
  },
  {
    coingeckoId: 'wen-4',
    symbol: 'WEN',
    name: 'Wen',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/34856/large/wen-solana.png?1707872119',
    address: 'WENWENvqqNya429ubCdR81ZmD69brwQaaBYY6p3LCpk',
    pairAddress: '7BZzoP3QB2zK3R7WqRzjS5fpeeErgdy3HGzxXrN97aEY',
    website: 'https://www.wenwencoin.com',
    x: 'https://twitter.com/wenwencoin',
    telegram: 'https://t.me/wenwencoinsol',
  },
  {
    coingeckoId: 'wuffi',
    symbol: 'WUF',
    name: 'Wuffi',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/36933/large/WUFFI.jpg?1720613603',
    address: '73xsLcBnLnc9bh81cqVKqj8uEyiarXng5ZwJuTbnVebG',
    pairAddress: '8qDVQ9KWnBD2CMVqcFdvjfR5m6gPJ4Bt9sod8G2Yj9zU',
    website: 'https://www.wuffi.io',
    x: 'https://x.com/WUFFI_Inu',
    telegram: 'https://t.me/wuffi_token',
  },
  {
    coingeckoId: 'myro',
    symbol: '$MYRO',
    name: 'Myro',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/32878/large/MYRO_200x200.png?1699709942',
    address: 'HhJpBhRRn4g56VsyLuT8DL5Bv31HkXqsrahTTUCZeZg4',
    pairAddress: '5WGYajM1xtLy3QrLHGSX4YPwsso3jrjEsbU1VivUErzk',
    website: 'http://myrothedog.com',
    x: 'https://twitter.com/myrosol',
    telegram: 'https://t.me/myrosol',
  },
  {
    coingeckoId: 'xborg',
    symbol: 'XBG',
    name: 'XBorg',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/39830/large/XBorg_Logo.png?1724209192',
    address: 'XBGdqJ9P175hCC1LangCEyXWNeCPHaKWA17tymz2PrY',
    pairAddress: 'F6N4UKdwzraCd3U3vn7J1CYtiwifkjTh5eQAixP2mpQH',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'collaterize',
    symbol: '$COLLAT',
    name: 'Collaterize',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/54178/large/Collaterize_Logo_200px.png?1738587819',
    address: 'C7heQqfNzdMbUFQwcHkL9FvdwsFsDRBnfwZDDyWYCLTZ',
    pairAddress: 'DeAWLtRGAqCW7imV1jSC9NZkRKKGStFC1U7eDFBRxryR',
    website: 'https://www.collaterize.com/',
    x: 'https://x.com/collaterizehq',
    telegram: 'https://t.me/collaterizecommunity',
  },
  {
    coingeckoId: 'weatherxm-network',
    symbol: 'WXM',
    name: 'WeatherXM',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/38154/large/weatherxm-network-logo.png?1716668976',
    address: 'wxmJYe17a2oGJZJ1wDe6ZyRKUKmrLj2pJsavEdTVhPP',
    pairAddress: 'HMDXYYwRqes1LQVRbxVfVGRTYq93XehqKudMMrr4kdrn',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'solana-social-explorer',
    symbol: 'SSE',
    name: 'Solana Social Explorer',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/54214/large/8tVJPrj6_400x400.jpg?1738799750',
    address: 'H4phNbsqjV5rqk8u6FUACTLB6rNZRTAPGnBb8KXJpump',
    pairAddress: 'HDt4asuvNjWn1Y5mV2R3sPXf54hC911ANYihU8HtmK7z',
    website: 'https://www.sse.gg/',
    x: 'https://x.com/usetapestry?lang=en',
    telegram: '',
  },
  {
    coingeckoId: 'lingo',
    symbol: 'Lingo',
    name: 'Lingo',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/52647/large/Lingo_200x200.png?1733914947',
    address: 'GWZGj6AM4pkWxQW6bifE6JChSRf2hEQFWFkYC4REaL7H',
    pairAddress: 'EhH81sqxGKja2ryKkT6xooZRRWYnzCSWps62TRi8mSfp',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'carrot-2',
    symbol: 'CRT',
    name: 'Carrot',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/50489/large/Carrot-token-coingecko.png?1727934458',
    address: 'CRTx1JouZhzSU6XytsE42UQraoGqiHgxabocVfARTy2s',
    pairAddress: '8zdC6PtvKWN1c95Cez4CpsBgMep7ddu9jFW158Ux146j',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'der-daku',
    symbol: 'Der Daku',
    name: 'Daku ',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/53161/large/final-image_2.jpg?1735464409',
    address: 'HRiLLm6hYiSdniFGjvcSvQ7XJrA8YSoktcqFbWjmpump',
    pairAddress: 'DTaGDCPF52BCsihu5intM6pKAHQkLrHnoTzShtgwt5gu',
    website: 'https://toekn.com/dakucoin',
    x: 'https://x.com/dakucoin',
    telegram: 'https://t.me/dakucoinsol',
  },
  {
    coingeckoId: 'central-african-republic-meme',
    symbol: 'CAR',
    name: 'Central African Republic Meme',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/54297/large/car.jpg?1739153066',
    address: '7oBYdEhV4GkXC19ZfgAvXpJWp2Rn9pm1Bx2cVNxFpump',
    pairAddress: 'Bx5pAzBqbuYH5yT93XCoShDka6d6vz9AzBddG7zE9syh',
    website: 'https://www.carmemecoin.com/',
    x: 'https://x.com/CARMemecoinNews',
    telegram: '',
  },
  {
    coingeckoId: 'send-2',
    symbol: 'SEND',
    name: 'Send',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/39222/large/photo1719676966.jpeg?1721182505',
    address: 'SENDdRQtYMWaQrBroBrJ2Q53fgVuq95CV9UPGEvpCxa',
    pairAddress: 'ESr8SbVGgbMRCgCDDfL9x8DwPGLdAtgLLKKGx3UUKoaq',
    website: 'https://thesendcoin.com/',
    x: 'https://x.com/thesendcoin',
    telegram: '',
  },
  {
    coingeckoId: 'open-ticketing-ecosystem',
    symbol: 'opn',
    name: 'OPEN Ticketing Ecosystem',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/36612/large/TOKEN.png?1711975511',
    address: 'J1YnyKzmxBwFkPftvZexnHTm4Am7JnmWydhxtXdwEmMv',
  },

  {
    coingeckoId: 'crow-with-knife',
    symbol: 'CAW',
    name: 'crow with knife (Wormhole)',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/36067/large/200px.png?1710405601',
    address: '9niFQK8MsParjSxhYQ3Ys2a6zHmsEuKSB1M7wwdvZ7bj',
    pairAddress: 'r5ZNvv1VUBhPdJjyF6JftLkTAYiJKvuLRwWR8pTi19A',
    website: 'https://medium.com/@cronoscrocrow/777burn-66f082ede839',
    x: 'https://twitter.com/crow_with_knife',
    telegram: 'https://t.me/crowwithknife',
  },
  {
    coingeckoId: 'ora-coin',
    symbol: 'ORA',
    name: 'ORA Coin',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/51812/large/ORA_Token.png?1732029092',
    address: 'BPYhCMNao2XG4UR771LurHrwUg3rcp76jmg4XFfAacvg',
    pairAddress: '49fx19DJkr5nUfWKbLBeAGyU9vSayAkifcMQpVaK1Mg9',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'bertram-the-pomeranian',
    symbol: 'Bert',
    name: 'Bertram The Pomeranian',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/51480/large/Bertram_The_Pomeranian.png?1731404649',
    address: 'HgBRWfYxEfvPhtqkaeymCQtHCrKE46qQ43pKe8HCpump',
    pairAddress: 'BmsZE6TkZYskyS1PatPKRyyazGdxWFxdia4BuvLg9AgY',
    website: 'https://www.bert.global/',
    x: 'https://x.com/bertcoincto',
    telegram: 'https://t.me/bertsolanaportal',
  },
  {
    coingeckoId: 'kin',
    symbol: 'KIN',
    name: 'KIN',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/959/large/image.png?1721122241',
    address: 'kinXdEcpDQeHPEuQnqmUgtYykqKGVFq6CeVX5iAHJq6',
    pairAddress: '6kmMMacvoCKBkBrqssLEdFuEZu2wqtLdNQxh9VjtzfwT',
    website: 'https://www.reddit.com/r/kin/s/pGS3QUnXlZ',
    x: 'https://x.com/Kin_Ecosystem',
    telegram: 'https://t.me/KinCryptoTelegram',
  },
  {
    coingeckoId: 'moby-ai',
    symbol: 'MOBY',
    name: 'Moby AI',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/53613/large/PFP_V3.png?1736888476',
    address: 'Cy1GS2FqefgaMbi45UunrUzin1rfEmTUYnomddzBpump',
    pairAddress: 'AemYRZmJryzAQ9Z4RLfUBLnPRUY5ecooc94EJvemfti4',
    website:
      'https://pump.fun/coin/Cy1GS2FqefgaMbi45UunrUzin1rfEmTUYnomddzBpump',
    x: 'https://x.com/mobyagent',
    telegram: '',
  },
  {
    coingeckoId: 'hive-ai',
    symbol: 'BUZZ',
    name: 'Hive AI',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/53442/large/fDd5tYZe_400x400.jpg?1736377018',
    address: '9DHe3pycTuymFk4H4bbPoAJ4hQrr2kaLDF6J6aAKpump',
    pairAddress: 'J2p6tgZDkvtHQ3VfbGRjzHJNLrqFgGfvjJsp2K7HX5cH',
    website: 'https://www.askthehive.ai/',
    x: 'https://x.com/askthehive_ai',
    telegram: '',
  },
  {
    coingeckoId: 'rift-ai',
    symbol: 'RIFT',
    name: 'RIFT AI',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/54216/large/IMG_5397.jpeg?1738824846',
    address: 'jUpa2aDCzvdR9EF4fqDXmuyMUkonPTohphABLmRkRFj',
    pairAddress: 'AMEdCZRmPQSnnsVoGjtTm3dJT2LfiBi1eEMjN137q31c',
    website: 'https://rift.ai/',
    x: 'https://x.com/fchainxyz',
    telegram: '',
  },
  {
    coingeckoId: 'quiztok',
    symbol: 'qtcon',
    name: 'Quiztok',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/8208/large/QTCON.png?1696508415',
    address: 'DkNihsQs1hqEwf9TgKP8FmGv7dmMQ7hnKjS2ZSmMZZBE',
  },
  {
    coingeckoId: 'the-doge-nft',
    symbol: 'DOG',
    name: 'The Doge NFT (Wormhole)',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/18111/large/Doge.png?1696517615',
    address: 'B9u8h65uM1oifqmP82VyUDb68iG2fKfZiyubmNMtu3h7',
    pairAddress: 'E7AEy7w3pcTk4xWMwpAEx6Pgsmw9PBFe1EGeGSD5fHDQ',
    website: 'https://www.ownthedoge.com',
    x: 'https://twitter.com/ownthedoge',
    telegram: 'https://t.me/ownthedoge',
  },
  {
    coingeckoId: 'samoyedcoin',
    symbol: 'SAMO',
    name: 'Samoyed Coin',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/15051/large/IXeEj5e.png?1696514710',
    address: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
    pairAddress: 'EyDgEU9BdG7m6ZK4bYERxbN4NCJ129WzPtv23dBkfsLg',
    website: 'https://samoyedcoin.com',
    x: 'https://x.com/samoyedcoin',
    telegram: 'https://t.me/samoyedcoin',
  },
  {
    coingeckoId: 'helium-iot',
    symbol: 'IOT',
    name: 'Helium IOT',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/29880/large/Iot_Icon.png?1696528805',
    address: 'iotEVVZLEywoTn1QdwNPddxPWszn3zFhEot3MfL9fns',
    pairAddress: 'Cx6WqD4ViGZArdA3nPcneNBJxECftm36CZbtdb7jw9gP',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'nodecoin',
    symbol: 'NC',
    name: 'Nodecoin',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/53158/large/200x200_White_-_Nodepay_Logomark.png?1735462700',
    address: 'B89Hd5Juz7JP2dxCZXFJWk4tMTcbw7feDhuWGb3kq5qE',
    pairAddress: 'E1wnaH2ZQvcB5hDWZe4JpivpjByLGP4uwFcMZb25FH3Y',
    website: 'https://www.nodepay.ai/',
    x: 'https://x.com/nodepay_ai',
    telegram: 'https://t.me/nodepaycommunitychat',
  },
  {
    coingeckoId: 'realio-network',
    symbol: 'RIO',
    name: 'Realio Network',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/12206/large/Rio.png?1696512042',
    address: 'HELn8rSM1rp8vAjNH4NYXzX6FvCbwWMGqLfaMgiBnZFV',
    pairAddress: 'CL68fLtYErKT5Fz35Lud7WcjvoMHUnZj2xchakFa6Li',
    website: '',
    x: '',
    telegram: '',
  },
  {
    coingeckoId: 'luna-by-virtuals',
    symbol: 'LUNA',
    name: 'Luna by Virtuals (Wormhole)',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/50880/large/luna.png?1729478763',
    address: '9se6kma7LeGcQWyRBNcYzyxZPE3r9t9qWZ8SnjnN3jJ7',
    pairAddress: 'DazumoDdMJB1Geeef9uMnM6zyU7Wtr3FnHbjyMJPso3D',
    website: 'https://app.virtuals.io/virtuals/68',
    x: 'https://x.com/luna_virtuals',
    telegram: 'https://t.me/virtuals/6595',
  },
  {
    coingeckoId: 'orbit-3',
    symbol: 'GRIFT',
    name: 'ORBIT',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/52598/large/4.png?1733741120',
    address: 'GekTNfm84QfyP2GdAHZ5AgACBRd69aNmgA5FDhZupump',
    pairAddress: '7dXUXn2dxTydHi2yWqvvqJwEWoB9mLFTh4hzDDowKVJY',
    website: 'https://www.orbitcryptoai.com',
    x: 'https://x.com/orbitcryptoai',
    telegram: '',
  },
  {
    coingeckoId: 'loopin-network',
    symbol: 'LOOPIN',
    name: 'LooPIN',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/51810/large/photo_2024-11-19_03-34-39.jpg?1732010671',
    address: 'CHX3FSxGYSJ2LHeQTcGp2oMAoBNngtJ73jsuamMUnZQx',
    pairAddress: '9ZR9c2Tsj1W8Uk3jSMMSqJZAjcTLBocUiRnd17SErQbD',
    website: 'https://loopin.network',
    x: 'https://x.com/loopin_network',
    telegram: '',
  },
  {
    coingeckoId: 'hyperskids',
    symbol: 'HYPERSKIDS',
    name: '$HYPERSKIDS',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/54173/large/20250202_205704.png?1738561742',
    address: 'GwkEDwePTa6aFosh9xzAniGK1zvLrQ5yPJfLnqwmuyhG',
    pairAddress: 'Az6TtMc28y4cHwvFkGQ59ZNUeXtEyt3rucuzFWL7yvtr',
    website: 'http://HypersKidsToken.com',
    x: 'https://x.com/hyperskidstoken',
    telegram: 'https://t.me/HYPERSKIDSPORTAL',
  },
  {
    coingeckoId: 'sanctum-2',
    symbol: 'CLOUD',
    name: 'Cloud',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/38485/large/CLOUD_128x128.png?1721331750',
    address: 'CLoUDKc4Ane7HeQcPpE3YHnznRxhMimJ4MyaUqyHFzAu',
    pairAddress: 'F1KKNyUCsQcZLRjwQ4abX6Ri8gDAQ46nHwSHFKA5sFQv',
    website: 'http://sanctum.so/',
    x: 'https://x.com/sanctumso',
    telegram: '',
  },

  {
    coingeckoId: 'green-satoshi-token',
    symbol: 'GST',
    name: 'GST',
    logoUrl:
      'https://coin-images.coingecko.com/coins/images/21841/large/gst.png?1696521196',
    address: 'AFbX8oGjGpmVFywbVouvhQSRmiW2aR1mohfahi4Y2AdB',
    pairAddress: '5NLeMabMyuJQUbvXNfVyUPbtYKwTXBesfmFmDswbgqUz',
    website: '',
    x: '',
    telegram: '',
  },

  {
    coingeckoId: '',
    symbol: 'TROLLANA',
    name: 'TROLLANA',
    logoUrl: '',
    address: '3XD6TXUErsBsztVsGuZqVpbaEuafn3N3orwHqxHmYtWw',
    pairAddress: 'fep1e1r1zcr8gwvtyxuacccp1zkvlvsumdokyjprjcmy',
    website: 'https://trollana.vip/',
    x: 'https://x.com/trollana_solana',
    telegram: 'https://t.me/TROLLANAOfficial',
  },
]
